# Dependencies
markdown:         redcarpet
highlighter:      true
gems:             [jekyll-paginate]
# Permalinks
permalink:        pretty

# Setup
title:               Humboldt Data Science
tagline:             'Statistical Methods and Python tools'
description:         'Class provided by the Cosmology Group of Prof. Marek Kowalski of the <a href="https://www.physik.hu-berlin.de/de/astro" target="_blank">Humboldt Universitaet zu Berlin.</a>'

url:                 http://github.com/HUDataScience
<<<<<<< HEAD
baseurl:             ""
=======
baseurl:             'http://hudatascience.github.io'
huastrourl:          https://www.physik.hu-berlin.de/de/astro
>>>>>>> master
paginate:            5
paginate_path:      "/classes/page:num/"
# About/contact
huastrourl:          https://www.physik.hu-berlin.de/de/astro
author:
  name:              Humboldt Cosmology Team
  url:               
  email:             humboldtcosmo@gmail.com

# Custom vars
version:             0.2.0
