# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# Permalinks are decrepated
# relative_permalinks: true

# Setup
title:               Humboldt Data Science
tagline:             'Statistical Analysis and Python tools'
description:         'Website built using <a href="http://jekyllrb.com" target="_blank">Jekyll</a> using <a href="https://twitter.com/mdo" target="_blank">@mdo</a> Lynaon theme..'
url:                 http://github.com/HUDataScience
baseurl:             'http://hudatascience.github.io/'
paginate:            5

# About/contact
author:
  name:              Humboldt Cosmology Team
  url:               
  email:             humboldtcosmo@gmail.com

# Custom vars
version:             0.1.0
